set_led_colour:
  name: Set LED Colour
  description: >
    Set the colour of the LED on the mug
  target:
    entity:
      integration: ember_mug
  fields:
    rgb_color:
      name: rgb-color
      description: Color for the LED in RGB format.
      advanced: true
      example: "[255, 100, 100]"
      selector:
        color_rgb:

set_target_temp:
  name: Set Mug Temperature
  description: >
    Set the target temperature for the mug
  target:
    entity:
      integration: ember_mug
  fields:
    target_temp:
      name: Target Temp
      description: Set the target temperature for the mug
      required: true
      example: "55.5"
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "C"

set_mug_name:
  name: Set a name for your Ember Mug
  description: >
    Set a name for your Ember Mug
  target:
    entity:
      integration: ember_mug
  fields:
    name:
      name: Mug Name
      description: A name for your mug. Must be safe for Bluetooth devices.
      required: true
      example: "EMBER"
      default: "EMBER"
